### PR TITLE
Build: Add `make dist` rule

### PR DESCRIPTION
**Pull request by clarete**
The new rule outputs a `.tar.gz` file containing the all `.mec` files
and the `meme` binary.

### CODE REVIEW

**Comment by thiago-silva** [comment]
@clarete, I added a lil dirty script into DIST to install files into /usr/local. You might want to see it and make it cleaner, as I'm not very familiar with gnu install.

I also changed order of lookup of `meme.config` (first at $HOME, then at /etc/). I'm not so sure how to lookup `core.img` at this point. Maybe the best thing for now would be to have an entry in meme.config pointing to it. In that case, since both the VM class and CoreImage expects a core filepath, these will need changing.

**Comment by clarete** [comment]
Hi @thiago-silva I think you forgot to add the `install.sh` file!

I'd separate the `make dist` from the `make install` target. However, I would indeed write `make dist` in terms of `make install`. So `make dist` is just a `make install` that points to a temporary `root` directory that is bundled in a `.tar.gz` package.

Regarding the `core.img` I do think it's a great idea to add it to the `meme.config` file, especially because we're all about dynamic and configurable behavior. If it wasn't useful for the user to change that, I'd just set that path in compile time.

I'd have to read the FHS a little bit more (it's been a while lol) but I think that the `.me`, `.mec` and `core.img` could be installed under `/usr/lib/memetalk-<version>/` (not sure what you think about the `<version>` bit though. That's what most distros do to allow multiple versions of python in the same system).

Whatcha think?

**Comment by thiago-silva** [comment]
Of course I did :/ ...sigh....
well, it's small, so here:

```
#!/bin/sh

DEST="/usr/local"

install meme $DEST/bin
install -m 644 core.img $DEST/lib/memetalk
install -m 644 meme.config.sample /etc/meme.config
cp -r central $DEST/lib/memetalk
```

 I was not doing a `make install` target though. Just a script in the tar.gz to move things to the system directories (see above). I still don't know about tagging the directory name with a version though. Maybe for now it may help, while we don't tag the .mec files with versions etc. But once we do, I hope we will only need a `/lib/memetalk`.

**Comment by thiago-silva** [comment]
merged on master

**Pull request closed without merging**
